# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
##default_velocity_scaling_factor: 0.1
#default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_gripper:
    has_velocity_limits: true
    max_velocity: 3
    max_position: 0.019
    min_position: -0.01
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_sub:
    has_velocity_limits: true
    max_velocity: 3
    max_position: 0.019
    min_position: -0.01
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint1:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint2:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint3:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint4:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  left_virtual_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  left_virtual_yaw_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper:
    has_velocity_limits: true
    max_velocity: 4.8
    max_position: 0.019
    min_position: -0.01
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_sub:
    has_velocity_limits: true
    max_velocity: 4.8
    max_position: 0.019
    min_position:  -0.01
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint1:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint2:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint3:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint4:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  right_virtual_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  right_virtual_yaw_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
